name: Meeting
author: Tierney Cyren (@bnb)
description: A GitHub Action to create issues that detail meetings
runs:
    using: 'node12'
    main: 'dist/index.js'
inputs:
    markdown-join-instructions:
        description: 'Path to checked-in Markdown file detailing how folks can join the meeting. Generally, ~/.github/meeting/ is going to be the best location.'
        required: true
    markdown-minutes-base:
        description: 'Path to checked-in Markdown file defining the structure of the agenda. Generally, ~/.github/meeting/ is going to be the best location.'
        required: true
    github-token:
        description: 'GitHub Token used for authentication. See the following link for more details: https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token'
        required: true
    invites:
        description: 'String of people or teams to invite via @mention'
        required: false
    observers:
        description: 'String of people or teams to invite via @mention'
        required: false